version: '2'
services:
  dabasubscribber:
    image: node:6.13.0
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      -  /etc/localtime:/etc/localtime:ro
      - ./srv:/app
      - ./dist:/dist
      - ./dist/log:/log
    network_mode: "host"
    environment:
      - isredissubscriber=true
      - MONGO_URL=mongodb://dabauser:daba159@127.0.0.1/daba
      - rooturl=http://api.nuistiot.com:30049
      - listenport=30049
      - logdir=/log
    ports:
       - "30049:30049"
    expose:
       - "30049"
