version: '2'
services:
  nginx:
      image: nginx
      restart: always
      expose:
         - "50000"
      ports:
          - "50000:50000"
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ./dist:/usr/share/nginx/html
      network_mode: "host"
