version: '2'
services:
  nginx80:
      image: nginx
      restart: always
      expose:
         - "80"
      ports:
          - "80:80"
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - ./nginx/default80.conf:/etc/nginx/conf.d/default.conf
          - ./dist:/usr/share/nginx/html
      network_mode: "host"
